### ISSUE TITLE
Specify the target os/arch for build and deploy

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/odo#6178] opened 2022-09-28 22:32 UTC
/kind feature

## Which functionality do you think we should add?

When building and deploying images with `odo` there should be a way to specify the target os/arch similar to the `--platform` option for `podman build`.

## Why is this needed?

It should be possible to build and deploy from arm64 local systems (like Mac M1) to Kubernetes clusters that do not have the corresponding arch.

**Comment by rm3l** [comment] 2022-10-06 12:36
**Grooming call (2022-10-06)**

- Also applicable to `odo dev`
- Best option to add a flag
- Should be handled the same way as #6200 (related to #6185)

**Comment by valaparthvi** [comment] 2023-02-07 12:55
/close
Duplicate of #6421

Feel free to reopen if you think otherwise.

**Closed by valaparthvi** 2023-02-07 12:55 UTC
Labels: kind/feature, area/deploy
