### ISSUE TITLE
odo v2.4.1 / SBO 1.0 failure to push newly created postgres DB link

### ISSUE THREAD

**Issue by ajm01** [redhat-developer/odo#5207] opened 2021-11-05 14:08 UTC
/kind bug

## What versions of software are you using?

**Operating System: RH 8.4**

**Output of `odo version`: v2.4.1 (dbf7ad592)**

## How did you run odo exactly?
```odo link PostgresCluster/mydb```
```odo push```

## Actual behavior
```Creating Kubernetes resources for component mysboproj
 âœ"  Waiting for component to start [2ms]
 âœ—  Failed to start component with name "mysboproj". Error: Failed to create the component: failed to create service(s) associated with the component: more than one item found in the result: [[<interface {} Value>] [-pguser-] [<interface {} Value>]]
```

## Expected behavior
odo link established in kubernetes

**Comment by feloy** [comment] 2021-11-05 15:16
Thanks @ajm01 for opening this issue.

Could you please share the command used to create the service, and the content of the file present in the `kubernetes` directory?

Also, could you please indicate the exact version of the PostgreSQL operator used? (the output of the command `odo catalog list services` would be enough)

**Comment by ajm01** [comment] 2021-11-05 15:49
Hi - for sure, here is the requested info:
I am using the v5.x version of Crunchy:
```[root@revisor1 ~]# odo catalog list services
Services available through Operators
NAME                                CRDs
postgresoperator.v5.0.3             PostgresCluster
service-binding-operator.v1.0.0     BindableKinds, ServiceBinding, ServiceBinding
[root@revisor1 ~]#
```

I actually created the DB Cluster ahead of time using the v5.x Crunchy Postgre Operator documentation. So - from the command line I issued:
```kubectl apply -k kustomize/postgres```

Once i created the link using odo, i listed it to see:
```[root@revisor1 jpa]# odo service list
NAME                     MANAGED BY ODO     STATE     AGE
PostgresCluster/mydb     No                           18h38m41s

Failed to fetch services for operator(s): "service-binding-operator.v1.0.0/BindableKinds"
[root@revisor1 jpa]#
```

So, I see the Managed by odo col reports 'No' - so not sure if that is because i created the db service/cluster ahead of time? and if that is a problem?

finally, the contents of the file in the kubernetes dir:
```[root@revisor1 kubernetes]# cat odo-service-mysboproj-postgrescluster-mydb.yaml
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  creationTimestamp: null
  name: mysboproj-postgrescluster-mydb
spec:
  application:
    group: apps
    name: mysboproj-app
    resource: deployments
    version: v1
  bindAsFiles: true
  detectBindingResources: true
  services:
  - group: postgres-operator.crunchydata.com
    kind: PostgresCluster
    name: mydb
    version: v1beta1
status:
  secret: ""
```

**Comment by ajm01** [comment] 2021-11-05 15:50
Here is a link to the instructions i followed at the v5 Crunchy doc site:
https://access.crunchydata.com/documentation/postgres-operator/v5/quickstart/

**Comment by feloy** [comment] 2021-11-05 16:27
Did you update the file `kustomize/postgres/postgres.yaml` before running the command `kubectl apply -k kustomize/postgres`?

(I cannot reproduce the error with the default file provided in the example)

**Comment by ajm01** [comment] 2021-11-05 16:36
oh, yes - i did - to point to the default ns for the location of the postgres db cluster pods - same place where my odo project pod is running. And this is running against minikube kubernetes if that is pertinent too.

**Comment by kadel** [comment] 2021-11-10 14:33
> So, I see the Managed by odo col reports 'No' - so not sure if that is because i created the db service/cluster ahead of time? and if that is a problem?

This should not be a problem.


I finally managed to reproduce this. It looks like the errors is thrown only when there is Service Binding Operator installed on the cluster.
Due to some permission issues we had to start using Service Binding as library from client side (from odo). Odo is still using Service Biding, but it is not leveraging the Operator. It is directly importing code from Service Binding Operator and does binding on its own without involving installed Operator.
It looks like this is causing some troubles here.


/priority high
/area service-binding

**Comment by feloy** [comment] 2021-11-10 16:03
It seems that the annotations in the PostgreSQL CRD are not supported by the version of the library odo is using:

```
metadata:
  annotations:
    service.binding: path={.metadata.name}-pguser-{.metadata.name},objectType=Secret
    service.binding/database: path={.metadata.name}-pguser-{.metadata.name},objectType=Secret,sourceKey=dbname
    service.binding/type: postgresql
    service.binding/username: path={.metadata.name}-pguser-{.metadata.name},objectType=Secret,sourceKey=user
```

(Note that these annotations do not appear if the Service Binding Operator is not installed)

As a workaround, you can set the annotations in the Custom Resource, hardcoding the name of your resource:

```
kubectl edit postgresclusters.postgres-operator.crunchydata.com mydb
```

then add the following annotations:

```
    service.binding: path=mydb-pguser-mydb,objectType=Secret
    service.binding/database: path=mydb-pguser-mydb,objectType=Secret,sourceKey=dbname
    service.binding/type: postgresql
    service.binding/username: path=mydb-pguser-mydb,objectType=Secret,sourceKey=user
```

**Comment by ajm01** [comment] 2021-11-10 17:17
I can verify that with the work-around mentioned above by @feloy the link does work and my sample app worked successfully.

**Comment by feloy** [comment] 2021-11-10 17:20
Should be fixed by #5221

**Comment by dharmit** [comment] 2021-11-29 12:28
Before 1.0, library made sense to use vs. SB Operator. But with 1.0 hard-coded annotations help provide better UX.
So figure out if SB library 1.0 has hard-coded annotations.
Irrespective, we move back to using SB Operator because using library was temporary.

**Comment by kadel** [comment] 2021-11-29 17:21
Tested that updating verssion of sbo library that odo uses to 1.0 solves (https://github.com/openshift/odo/pull/5255) this problem

**Comment by kadel** [comment] 2023-02-08 16:17
`odo link` was remove in odo v3
/close

**Closed by kadel** 2023-02-08 16:17 UTC
Labels: kind/bug, priority/High, area/binding, v2
