### ISSUE TITLE
Homebrew forumla broken?

### ISSUE THREAD

**Issue by ryannix123** [redhat-developer/odo#6558] opened 2023-02-01 11:26 UTC
odo fails to update:

```
Fetching odo-dev
==> Cloning https://github.com/redhat-developer/odo.git
Updating /Users/rnix/Library/Caches/Homebrew/odo-dev--git
fatal: couldn't find remote ref refs/heads/master
Error: odo-dev: Failed to download resource "odo-dev"
Failure while executing; `git fetch origin` exited with 128. Here's the output:
fatal: couldn't find remote ref refs/heads/master
```

**Comment by kadel** [comment] 2023-02-01 11:56
Hi @ryannix123 I'm not able to reproduce this :-/

Can you share the exact `brew` command that you are using? Is it `brew install odo-dev` or `brew install --HEAD odo-dev`?


The output that you shared is strange. It looks like it is trying to fetch `master` branch, but odo repo switched to `main`, more than a year back.

Is it possible that you are still using the old homebrew tap from https://github.com/kadel/homebrew-odo?

If yes, then you can remove it and use `odo-dev` from homebrew-core

```
brew uninstall kadel/odo/odo
brew untap kadel/odo

brew install odo-dev
```

**Comment by kadel** [comment] 2023-02-01 12:25
> Running these commands fixed the issue.

perfect
I'm closing this issue 
/close

If you encounter any problems let us know.

**Closed** 2023-02-01 12:25 UTC
Labels: needs-triage
