### ISSUE TITLE
Getting rid of `odo create` and instead use `odo component create`

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#953] opened 2018-11-08 15:17 UTC
I feel as though we should refactor the way that we are using commands as the scope of the project becomes *much* larger.

We should follow a `odo <component> <action>` for all commands. For example: `odo create` should just be `odo component create`.

It doesn't make sense to prioritize components over services / storage / etc and not follow the common conventions.

It does however make sense to continue to use the commands as aliases, for example, `odo create` will always relate to component, however, it won't show in our default --help menu / documentation.

At the moment our help menu looks like this:

```sh
Component Commands:
  component   Components of application.
  create      Create a new component
  delete      Delete an existing component
  describe    Describe the given component
  link        Link component to a service or component
  list        List all components in the current application
  log         Retrieve the log for the given component.
  push        Push source code to a component
  update      Update the source code path of a component
  watch       Watch for changes, update component on change

Other Commands:
  app         Perform application operations
  catalog     Catalog related operations
  project     Perform project operations
  service     Perform service catalog operations
  storage     Perform storage operations
  url         Expose component to the outside world

Utility Commands:
  help        Help about any command
  utils       Utilities for terminal commands and modifying Odo configurations
  version     Print the client version information
```

When in reality we can have this:

```sh
Commands:
  app         Perform application operations
  component   Perform component operations
  catalog     Catalog related operations
  project     Perform project operations
  service     Perform service catalog operations
  storage     Perform storage operations
  url         Expose component to the outside world

Utility Commands:
  help        Help about any command
  utils       Utilities for terminal commands and modifying Odo configurations
  version     Print the client version information
```

**Comment by jorgemoralespou** [comment] 2018-11-08 15:30
Reading the complete issue, where you're referring just to how the documentation shows, I'm ok with that.

**Comment by cdrage** [comment] 2018-11-08 15:42
@jorgemoralespou Yeah, I'm talking with regards to the documentation.

With the documentation, should we instead prioritize / change the documentation to show `odo component create` and *still* keep the alias?

**Comment by metacosm** [comment] 2018-11-08 15:44
I agree. If it was up to me, as stated in #779, I'd remove the aliases altogether ;)

**Comment by jorgemoralespou** [comment] 2018-11-08 17:07
-1 to remove the aliases.

**Comment by kadel** [comment] 2018-11-26 12:52
Closing this as a duplicate of #779. This is just splitting the same discussion to two places. Lets continue this in #779

**Closed by kadel** 2018-11-26 12:52 UTC
Labels: kind/docs, priority/Low, size/M, state/In Analysis
