### ISSUE TITLE
odo doesn't download extra stack files

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#6448] opened 2023-01-02 16:23 UTC
/kind bug
/priority high

## How did you run odo exactly?

```
odo init --name java-springboot-starter --devfile java-springboot --devfile-registry DefaultDevfileRegistry --devfile-version 2.0.0 --starter springbootproject
```

```
▶ odo dev
  __
 /  \__     Developing using the "java-springboot-starter" Devfile
 \__/  \    Namespace: test
 /  \__/    odo version: v3.4.0
 \__/

↪ Deploying to the cluster in developer mode
 •  Waiting for Kubernetes resources  ...
W0102 17:21:08.416538   76108 warnings.go:70] would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "tools" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "tools" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "tools" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "tools" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
Cleaning resources, please wait
Failed to delete inner loop resources: failed to gather resources for deletion: open /Users/tkral/Code/odo-examples/java-springboot-starter/kubernetes/deploy.yaml: no such file or directory
 ✗  unable to determine resources to delete: unable to read the resource: open /Users/tkral/Code/odo-examples/java-springboot-starter/kubernetes/deploy.yaml: no such file or directory
```

## Actual behavior

odo dev complains about missing files

## Expected behavior
`odo init` should download the whole Devfile stack. The Devfile stack is not just devfile.yaml, but also all extra files (https://github.com/devfile/registry/tree/main/stacks/java-springboot/2.0.0)

NOTES;
- Handle conflicts : download everything or nothing

**Comment by valaparthvi** [comment] 2023-01-03 09:56
I think the issue is with the git repo https://github.com/odo-devfiles/springboot-ex, it does not have the required files. The git repo also needs to be updated along with the stack.

**Comment by kadel** [comment] 2023-01-03 14:36
This is has nothing to do with the starter project. It is just about Devfile stacks. 

The Devfile stack can have some extra files alongside the devfile.yaml. Like in case of [2.0.0 java-springboot ](https://github.com/devfile/registry/tree/main/stacks/java-springboot/2.0.0). You can see that there are `kubernetes` and `docker` directories, those directories should be downloaded together with devfile.yaml

**Comment by rm3l** [comment] 2023-01-04 12:32
TODO
- Research if it is possible to download extra files using the Devfile library

**Comment by valaparthvi** [comment] 2023-01-05 11:02
> TODO
> 
>     * Research if it is possible to download extra files using the Devfile library

It still fails with the latest version of Devfile library.

**Comment by valaparthvi** [comment] 2023-01-13 14:34
I am going to close this issue since the original issue has been resolved, but I'll create a new one for the problem in https://github.com/redhat-developer/odo/issues/6448#issuecomment-1381894379.
/close

**Closed by valaparthvi** 2023-01-13 14:34 UTC
Labels: kind/bug, priority/High
