### ISSUE TITLE
watch on binary component does't work correctly

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#1117] opened 2018-12-07 18:47 UTC
It looks like that for binary components only the first chagne is correctly deteted. Anything after that is not :-(

```
odo create redhat-openjdk18-openshift:1.4 mysb --binary target/spring-boot-rest-http-1.5.17-5-SNAPSHOT.jar
odo push
odo watch

mvn package
#change is correctly detected by watch 

mvn package
# nothing is happening watch doesn't trigger anything
```

**Comment by geoand** [comment] 2018-12-10 08:00
Very weird... Let me check this

**Comment by geoand** [comment] 2018-12-10 08:22
@kadel I think I reproduce the problem.
It seems like watch is crashing, I see am seeing: 
```
I1210 10:18:21.926668   20777 watch.go:301] Copying file /home/gandrian/gowork/src/github.com/redhat-developer/odo/tests/e2e/examples/source/openjdk/target/javalin-hello-world-0.1-SNAPSHOT.jar to pod
 •  Waiting for pod to start  ...
I1210 10:18:21.999393   20777 occlient.go:1538] Waiting for deploymentconfig=java-odo-innn pod
 ✓  Waiting for pod to start
 •  Copying files to pod  ...
I1210 10:18:22.070001   20777 occlient.go:1562] Status of java-odo-innn-1-4zgdt pod is Running
I1210 10:18:22.070032   20777 occlient.go:1566] Pod java-odo-innn-1-4zgdt is running.
E1210 10:18:22.773696   20777 occlient.go:2539] Error while creating tar: &errors.errorString{s:"archive/tar: write too long"}
````

Unfortunately #1114 doesn't fix the issue either

**Comment by geoand** [comment] 2018-12-10 08:33
The problem with this is that I can't seem to reproduce it all the time :thinking:

**Comment by geoand** [comment] 2018-12-10 14:42
Another peculiar thing is that we never see the failure when doing `odo push`.
That get's me thinking that we have perhaps some sort of race condition that occurs between `mvn package` (which creates the jar) and `odo watch` (which watches for changes to that jar)

**Comment by jorgemoralespou** [comment] 2018-12-10 16:37
Can this be related to the broken pipe behavior seen in other issues (like https://github.com/redhat-developer/odo/issues/647)?

**Comment by geoand** [comment] 2018-12-10 16:44
I can't be certain, but this seems different

**Comment by kadel** [comment] 2018-12-11 03:49
> Can this be related to the broken pipe behavior seen in other issues (like #647)?

I think that this is a different issue.

**Comment by kadel** [comment] 2018-12-11 04:00
> @kadel @anmolbabu It seems to me that we need proper integration tests for `odo watch` so things like this and #1099 won't happen again.
> Who is the proper team member to take on such a task (I can obviously do it if needed :) )?

This is one of our biggest technical debts :-(   
@amitkrout could help us get started. Ideally,  we should collectively do it.

**Comment by amitkrout** [comment] 2018-12-11 06:00
> This is one of our biggest technical debts :-(
@amitkrout could help us get started. Ideally, we should collectively do it.

Yup i understand. I am new to ```GinkGo``` test frame work, so cannot not provide you the best suggestion atm as i am still understanding how this framework work. However this frame work looks similar to my previous project test frame work ```Godog```, so won't take much time to familiar with ```GinkGo```

Already we have the test structure in place. We just need to create a specifications file for reference, for example 

```
Given cluster is up and running
  initially
    should execute "odo create redhat-openjdk18-openshift:1.4 mysb ... "
    should execute "odo push"
    should execute "odo watch"
 [...]
```
And the same specification should be implemented in the test suite. I have created a separate issue #1121 to track the integration test coverage for watch on binary component and assigned it to me.

**Comment by geoand** [comment] 2018-12-11 07:07
@amitkrout I think that the basic tests for watch shouldn't too tricky to write. What we will definitely need is a way to stop the watch (which I am guessing will be done via `kill`).
The scenarios to test will probably be pretty similar to the ones we already test with push

**Comment by anmolbabu** [comment] 2018-12-11 07:14
> @amitkrout I think that the basic tests for watch shouldn't too tricky to write. What we will definitely need is a way to stop the watch (which I am guessing will be done via `kill`).
> The scenarios to test will probably be pretty similar to the ones we already test with push

@geoand @amitkrout There are basic tests already that I added(including to start watch as a process and then terminate it gracefully post completion of tests) it only needs to be now enhanced to not just look at whether the changes as expected are also observed from logs(as currently) but also create a url and verify the change in rest api(intially it was not added bcoz the nodejs-ex that we use currently in watch e2e has a UI validation of which I felt would complicate the PR https://github.com/redhat-developer/odo/pull/820 whose intial objective was to add some form of basic tests for watch command) I think its time we optimise it now to serve as complete end-to-end tests..
Note: https://github.com/redhat-developer/odo/pull/975 was a subsequent fix to PR above but to UTs

**Comment by geoand** [comment] 2018-12-11 07:21
@anmolbabu I wasn't aware of that test, :+1: 

Is there any specific reason why the test is not written in way that emulates how an external user/program would use watch?
I mean something like:
* `odo watch`
* sed a file (or in some cases is mv to ensure that a single file will be changed)
* ensure everything is OK (probably using the URL as you mentioned in the comment)
* repeat whatever else
* kill watch

**Comment by geoand** [comment] 2018-12-11 07:36
Also I would love to have the watch e2e tests in their own file so they can be tested independently of the cmp tests (which are many :) )

**Comment by anmolbabu** [comment] 2018-12-11 07:36
> @anmolbabu I wasn't aware of that test, 
> 
> Is there any specific reason why the test is not written in way that emulates how an external user/program would use watch?
> I mean something like:
> 
> * `odo watch`
> * sed a file (or in some cases is mv to ensure that a single file will be changed)
> * ensure everything is OK (probably using the URL as you mentioned in the comment)
> * repeat whatever else
> * kill watch

@geoand the above is the behaviour currently but the only difference is that we(I :P) are not doing a change that we can notice from the api exposed(because of reason in https://github.com/redhat-developer/odo/issues/1117#issuecomment-446096743)

**Comment by anmolbabu** [comment] 2018-12-11 07:37
> Also I would love to have the watch e2e tests in their own file so they can be tested independently of the cmp tests (which are many :) )

I agree...

**Comment by geoand** [comment] 2018-12-11 07:45
> > @anmolbabu I wasn't aware of that test,
> > Is there any specific reason why the test is not written in way that emulates how an external user/program would use watch?
> > I mean something like:
> > 
> > * `odo watch`
> > * sed a file (or in some cases is mv to ensure that a single file will be changed)
> > * ensure everything is OK (probably using the URL as you mentioned in the comment)
> > * repeat whatever else
> > * kill watch
> 
> @geoand the above is the behaviour currently but the only difference is that we(I :P) are not doing a change that we can notice from the api exposed(because of reason in [#1117 (comment)](https://github.com/redhat-developer/odo/issues/1117#issuecomment-446096743))

I guess what I'm trying to say is that, although the implementation is impressive, it is testing things that matter somewhat, but aren't true indicators of success (like you have mentioned as well).
Another thing is that I believe that if we use simple shell commands in the e2e tests (like is done currently in other tests), it will be a lot clearer what has been tested and what has not - not mention that removing extra testing infrastructure code will increase the test coverage :)

**Comment by anmolbabu** [comment] 2018-12-11 07:52
> > > @anmolbabu I wasn't aware of that test,
> > > Is there any specific reason why the test is not written in way that emulates how an external user/program would use watch?
> > > I mean something like:
> > > 
> > > * `odo watch`
> > > * sed a file (or in some cases is mv to ensure that a single file will be changed)
> > > * ensure everything is OK (probably using the URL as you mentioned in the comment)
> > > * repeat whatever else
> > > * kill watch
> > 
> > 
> > @geoand the above is the behaviour currently but the only difference is that we(I :P) are not doing a change that we can notice from the api exposed(because of reason in [#1117 (comment)](https://github.com/redhat-developer/odo/issues/1117#issuecomment-446096743))
> 
> I guess what I'm trying to say is that, although the implementation is impressive, it is testing things that matter somewhat, but aren't true indicators of success (like you have mentioned as well).
> Another thing is that I believe that if we use simple shell commands in the e2e tests (like is done currently in other tests), it will be a lot clearer what has been tested and what has not - not mention that removing extra testing infrastructure code will increase the test coverage :)
> 

Did you mean the `sed` like command usage instead of the current file open and write ?
I agree (may be bcoz they are more closer to real world case :) )...

> I am sorry that I hadn't payed attention to the implementation of the e2e test when you opened the PR, I would have raised my concerns earlier :(

No issues :) and I think the framework is used even by UT

**Comment by geoand** [comment] 2018-12-11 08:08
comment deleted by accident :(

**Comment by kadel** [comment] 2018-12-17 14:43
Do we have any indications what could be root cause of this issue?

**Comment by geoand** [comment] 2018-12-17 14:45
My best guess is that there is a race condition between maven creating the jar and odo watching for changes to it

**Comment by kadel** [comment] 2019-01-17 15:49
@anmolbabu Can you please estimate size for this task and add size label? You can find more info about labels https://github.com/redhat-developer/odo/wiki/Issue-labeling-system#size

**Comment by anmolbabu** [comment] 2019-01-18 05:16
sure @kadel

**Comment by anmolbabu** [comment] 2019-01-18 05:17
Ideally it could be `S` but at the moment I am not very sure what or where the fix should be so since the fix is not very obvious to me, I'll assign it `M` anyway I can always scale it down to `S` if found small at any later point in time

**Comment by anmolbabu** [comment] 2019-01-18 08:06
Fortunately enough, this seems to be fixed by my PR at https://github.com/redhat-developer/odo/pull/1125 and https://github.com/redhat-developer/odo-supervisord-image/pull/10

**Comment by anmolbabu** [comment] 2019-01-18 08:07
I'll add some tests just to be sure even they are ensured to be fixed for all runtimes

**Comment by anmolbabu** [comment] 2019-01-18 09:51
> I'll add some tests just to be sure even they are ensured to be fixed for all runtimes

Done. The PRs https://github.com/redhat-developer/odo-supervisord-image/pull/10 and https://github.com/redhat-developer/odo/pull/1125 now fix this with tests added

**Comment by anmolbabu** [comment] 2019-01-23 12:07
The PRs to fix this have been merged... Hence closing this issue

**Closed by anmolbabu** 2019-01-23 12:07 UTC
Labels: kind/bug, priority/High, size/M
