### ISSUE TITLE
odo commands output with colored text looks bad on Windows in cmd and powershell

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/odo#1072] opened 2018-12-04 07:55 UTC
## What versions of software are you using?
- Operating System: Windows 10 Pro
- Output of `odo version`: 0.0.17 built locally from master

## How did you run odo exactly?
In windows cmd or powershell

## Actual behavior
Special sympols are printed instead of bullets and colored check marks.
![image](https://user-images.githubusercontent.com/620330/49426561-c984bb00-f755-11e8-9ef4-0fb641d5de78.png)
![image](https://user-images.githubusercontent.com/620330/49426943-dbb32900-f756-11e8-98dd-67cb163b9d7b.png)

## Expected behavior
![image](https://user-images.githubusercontent.com/620330/49426687-1ff1f980-f756-11e8-90e7-7c5c73d7667b.png)

## Any logs, error output, etc?
N/A

**Comment by cdrage** [comment] 2018-12-04 16:13
@dgolovin @kadel 

Hey all,

So looks like the spinner actually works within Windows, the problem is the colouring..

https://github.com/fatih/color has been deprecated / unmaintained and colour support was never added for Windows. 

I'm going to investigate a different library or just remove it all-together.

**Comment by metacosm** [comment] 2018-12-04 21:36
Wondering if we're going to run in the same issue with the interactive mode… We might want to investigate: https://github.com/mattn/go-colorable

**Comment by geoand** [comment] 2018-12-05 07:37
@metacosm I have created a VirtualBox VM on my machine that I am guessing I can use to test the interactive mode PR and see if it fails or. What would you like me to test?

**Comment by cdrage** [comment] 2018-12-05 14:12
@metacosm Yeah, I was looking at https://github.com/mattn/go-colorable 

If we add a function that detects Windows and switches the standard `os.Stdout` it'll work :+1:

**Comment by kadel** [comment] 2019-01-17 15:46
@cdrage Can you please estimate size for this task and add size label?

**Comment by cdrage** [comment] 2019-03-18 20:07
Finally able to close this via #1211 !

**Closed by cdrage** 2019-03-18 20:07 UTC
Labels: kind/bug, priority/High, state/Ready
