### ISSUE TITLE
way too long info in PS1

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#549] opened 2018-06-28 07:43 UTC
When there is not app or/and no component the PS1 shows, too detailed information.
This is suitable for when user run `odo component` but in PS1 we should have something more concise.

```
[There's no active application.
You can create one by running 'odo application create <name>'./No component is set as current]
```
I think that something like `[<no application>/<no component>]` should be enough.

**Comment by cdrage** [comment] 2018-07-09 16:01
@kadel I'll assign this to myself and fix it. It *should* be reverting to blank instead, may need for me to update the regex.

**Comment by cdrage** [comment] 2018-07-09 19:56
@kadel 

The problem is that "There's no active application." prompt as well as "No component is set as current" is not returning an error code (this should error out).

The current PS1 implementation checks to see if there is an error code of 0 or 1 outputted and goes from there.

I've implemented this fix (with a more detailed description) here: https://github.com/redhat-developer/odo/pull/572

**Comment by kadel** [comment] 2018-07-10 14:55
> The problem is that "There's no active application." prompt as well as "No component is set as current" is not returning an error code (this should error out).

It shouldn't error out. The state with no active app or component is not error state.

**Comment by cdrage** [comment] 2018-07-10 15:07
@kadel I'd disagree that "There's no active application" would be an error rather than a print / prompt. As a compromise, if we add `-q` could we agree to make it error out if no active application / no component was found so that the PS1 script operates correctly based on error-code?

If not, we could always compromise and add regex / string checking to the PS1 instead of checking for error code.

**Comment by kadel** [comment] 2018-07-11 11:05
> As a compromise, if we add -q could we agree to make it error out if no active application / no component was found so that the PS1 script operates correctly based on error-code?

I don't like it to be honest. No active app or component is not an error state. We shouldn't make  `odo component -q` error out in those cases. Detecting if commands return empty string is easy as checking its return code.

**Comment by cdrage** [comment] 2018-07-16 16:41
@kadel Alright, no problem. I'll implement this with string checking rather than error checking!

**Comment by kadel** [comment] 2018-07-18 15:05
@cdrage https://github.com/redhat-developer/odo/issues/550 should be fixed before you do that.

**Closed** 2018-07-25 13:49 UTC
Labels: backlog, kind/task, priority/low, size/S
