### ISSUE TITLE
We can't create a component using image builder - redhat-openjdk18-openshift:1.4 

### ISSUE THREAD

**Issue by cmoulliard** [redhat-developer/odo#1262] opened 2019-01-31 10:27 UTC
## Bug

We can't create a component using the `redhat-openjdk18-openshift:1.4` and this command ` odo create redhat-openjdk18-openshift:1.4 sb2 --local ./src
` as initContainer will fail to start and will report such error

```
oc logs  sb2-springbootapp-1-f79q2 -c copy-files-to-volume
mkdir: cannot create directory '/mnt/app-root.setup-volume': Permission denied
tar: /opt/app-root: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
mv: cannot stat '/mnt/app-root.setup-volume': No such file or directory
```

Here is the pod's resource created by odo

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    openshift.io/deployment-config.latest-version: '4'
    openshift.io/deployment-config.name: sb2-springbootapp
    openshift.io/deployment.name: sb2-springbootapp-4
    openshift.io/scc: anyuid
  creationTimestamp: '2019-01-31T10:42:13Z'
  generateName: sb2-springbootapp-4-
  labels:
    deployment: sb2-springbootapp-4
    deploymentconfig: sb2-springbootapp
  name: sb2-springbootapp-4-f2qkm
  namespace: demo
  ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicationController
      name: sb2-springbootapp-4
      uid: dd034d7e-2544-11e9-b20d-107b44b03540
  resourceVersion: '12478526'
  selfLink: /api/v1/namespaces/demo/pods/sb2-springbootapp-4-f2qkm
  uid: deaa6c85-2544-11e9-b20d-107b44b03540
spec:
  containers:
    - args:
        - '-c'
        - /var/lib/supervisord/conf/supervisor.conf
      command:
        - /var/lib/supervisord/bin/supervisord
      env:
        - name: ODO_S2I_DEPLOYMENT_DIR
          value: /deployments
        - name: ODO_S2I_SCRIPTS_URL
          value: /usr/local/s2i
        - name: ODO_S2I_SCRIPTS_PROTOCOL
          value: 'image://'
        - name: ODO_S2I_SRC_BIN_PATH
          value: /tmp
      image: >-
        registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift@sha256:6c009f430da02bdcff618a7dcd085d7d22547263eeebfb8d6377a4cf6f58769d
      imagePullPolicy: IfNotPresent
      name: sb2-springbootapp
      ports:
        - containerPort: 8080
          name: 8080-tcp
          protocol: TCP
        - containerPort: 8443
          name: 8443-tcp
          protocol: TCP
        - containerPort: 8778
          name: 8778-tcp
          protocol: TCP
      resources: {}
      securityContext:
        capabilities:
          drop:
            - MKNOD
```

As you can see, the annotation `openshift.io/scc` is defined as `anyuid` and not as `restricted` when we make a test on minishift and by consequence the scc is not defined as such 

```
securityContext:
        capabilities:
          drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID
        runAsUser: 1000160000
```

odo version: 0.0.17
cluster: okd 3.11 running on centos7

**Comment by jorgemoralespou** [comment] 2019-01-31 13:12
@cmoulliard odo version 0.0.18 was released this week. Could you try with that version. There's been many changes in this area.

**Comment by kadel** [comment] 2019-01-31 13:43
> @cmoulliard odo version 0.0.18 was released this week. Could you try with that version. There's been many changes in this area.

I think that @cmoulliard is waiting for me to update homebrew.

**Comment by jorgemoralespou** [comment] 2019-01-31 13:57
In any case, and from discussion on mattermost, he's getting this error basically because he's pushing wrong files: `--local ./src` instead of `--local .` that is where his pom.xml file lives.

I would close this issue or change it to provide a more meaningful message if possible when this happens. :-D

**Comment by kadel** [comment] 2019-01-31 15:11
Yeh, something looks weird with that script, but I haven't  been  able to reproduce this :-(

**Comment by cmoulliard** [comment] 2019-01-31 17:23
I can resolve this problem after changing the SCC of the `serviceaccount` used to create the pod from `anyuid` to `restricted`

```
oc adm policy add-scc-to-user restricted -z default        
scc "restricted" added to: ["system:serviceaccount:demo:default"]
```

Questions:
- Do we have to change the UID/permissions needed/used to create within the initcontainer - >`mkdir -p $DEST.setup-volume` ?
- Do we have to document somewhere this problem and tell to the DevOps guy what to od ?

**Comment by jorgemoralespou** [comment] 2019-02-04 14:07
@geoand depending on the level of access to the cluster, you can:
- If you're admin, check the PV that got created
- If you're not, look into the PVC to see if there's any info
- Look to what is the default storage-class, which defines which storage type should be assigned if not explicitly requested one specific storage

**Comment by geoand** [comment] 2019-02-04 14:08
Thanks @jorgemoralespou!

I will check it out

**Comment by geoand** [comment] 2019-02-04 14:24
@jorgemoralespou 

`oc get pvc java-odo-bgdm-s2idata` yields:

```
{
    "apiVersion": "v1",
    "kind": "PersistentVolumeClaim",
    "metadata": {
        "annotations": {
            "pv.kubernetes.io/bind-completed": "yes",
            "pv.kubernetes.io/bound-by-controller": "yes"
        },
        "creationTimestamp": "2019-02-04T14:18:23Z",
        "finalizers": [
            "kubernetes.io/pvc-protection"
        ],
        "labels": {
            "app": "odo-bgdm",
            "app.kubernetes.io/component-name": "java",
            "app.kubernetes.io/component-type": "redhat-openjdk18-openshift",
            "app.kubernetes.io/component-version": "1.4",
            "app.kubernetes.io/name": "odo-bgdm"
        },
        "name": "java-odo-bgdm-s2idata",
        "namespace": "gandrian",
        "resourceVersion": "13256824",
        "selfLink": "/api/v1/namespaces/gandrian/persistentvolumeclaims/java-odo-bgdm-s2idata",
        "uid": "bae02f2a-2887-11e9-b20d-107b44b03540"
    },
    "spec": {
        "accessModes": [
            "ReadWriteOnce"
        ],
        "resources": {
            "requests": {
                "storage": "1Gi"
            }
        },
        "volumeName": "pv002"
    },
    "status": {
        "accessModes": [
            "ReadWriteOnce"
        ],
        "capacity": {
            "storage": "3Gi"
        },
        "phase": "Bound"
    }
}

```

`oc get pv pv002 -o json` yields:

```
{
    "apiVersion": "v1",
    "kind": "PersistentVolume",
    "metadata": {
        "annotations": {
            "pv.kubernetes.io/bound-by-controller": "yes"
        },
        "creationTimestamp": "2018-11-26T11:18:19Z",
        "finalizers": [
            "kubernetes.io/pv-protection"
        ],
        "name": "pv002",
        "resourceVersion": "13256822",
        "selfLink": "/api/v1/persistentvolumes/pv002",
        "uid": "fa5402f9-f16c-11e8-8803-107b44b03540"
    },
    "spec": {
        "accessModes": [
            "ReadWriteOnce"
        ],
        "capacity": {
            "storage": "3Gi"
        },
        "claimRef": {
            "apiVersion": "v1",
            "kind": "PersistentVolumeClaim",
            "name": "java-odo-bgdm-s2idata",
            "namespace": "gandrian",
            "resourceVersion": "13256820",
            "uid": "bae02f2a-2887-11e9-b20d-107b44b03540"
        },
        "hostPath": {
            "path": "/tmp/pv002",
            "type": ""
        },
        "persistentVolumeReclaimPolicy": "Recycle"
    },
    "status": {
        "phase": "Bound"
    }
}
```

This is a cluster that has been built using openshift-ansible but has a single all-in-one node

**Comment by cmoulliard** [comment] 2019-02-04 17:40
No storage class is defined. 

```
oc describe pv pv002
Name:            pv002
Labels:          <none>
Annotations:     pv.kubernetes.io/bound-by-controller=yes
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:
Status:          Bound
Claim:           gandrian/java-odo-bgdm-s2idata
Reclaim Policy:  Recycle
Access Modes:    RWO
Capacity:        3Gi
Node Affinity:   <none>
Message:
Source:
    Type:          HostPath (bare host directory volume)
    Path:          /tmp/pv002
    HostPathType:
Events:            <none>
```

**Comment by geoand** [comment] 2019-02-05 09:09
The proper `chcon` had also been applied to the host directories that contained the volumes

**Comment by cmoulliard** [comment] 2019-02-05 15:16
I resolved the issue as described FROM here https://github.com/snowdrop/openshift-infra/issues/121#issuecomment-460667169

**Closed as completed** 2019-02-05 15:34 UTC
Labels: kind/bug
