### ISSUE TITLE
failed to delete the ServiceBinding resource

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5797] opened 2022-06-07 07:43 UTC
/kind bug
/priority high

When using `odo dev`, the ServiceBinding is being created, and when we control+c the process, the ServiceBinding is deleted, but the logs say "Failed to delete the "ServiceBinding" resource"

**Comment by valaparthvi** [comment] 2022-08-02 13:45
I am unable to reproduce this issue on main. Tomas, can you test again?

**Comment by valaparthvi** [comment] 2022-08-04 11:34
@rm3l  could not reproduce this either, I am going to close this issue.

**Closed** 2022-08-25 07:02 UTC
Labels: kind/bug, priority/High, triage/not-reproducible
