### ISSUE TITLE
odo app describe does not honour manually created external route

### ISSUE THREAD

**Issue by amitkrout** [redhat-developer/odo#1256] opened 2019-01-30 14:49 UTC
[kind/bug]

## What versions of software are you using?
- Operating System: All supported platform
- Output of `odo version`: Tested on Odo master

## How did you run odo exactly?
1. Download minishift v1.30.0
2. start minishift
```
$ MINISHIFT_ENABLE_EXPERIMENTAL=y ./minishift start --extra-clusterup-flags "--enable=*,service-catalog,automation-service-broker,template-service-broker"
```
3. clone master and run make bin
4. ./odo create nodejs frontend
5. ./odo create python backend
6. ./odo link backend --component frontend
7. ./odo service create mysql-persistent
8. ./odo link mysql-persistent -w --component backend
9. ./minishift console
10. Create the external route with default port 8080 for both frontend and backend
11. ./odo app describe
```
$ ./odo app describe
Application Name: node-example-app has 2 component(s) and 1 service(s):
--------------------------------------
Component Name: backend
Type: python
Source: file:///Users/amit/Nightlycdkbuilds/v1.30.0

URLs
 - http://backend-node-example-app-myproject.192.168.64.3.nip.io exposed via 0
--------------------------------------
Component Name: frontend
Type: nodejs
Source: file:///Users/amit/Nightlycdkbuilds/v1.30.0

URLs
 - http://frontend-node-example-app-myproject.192.168.64.3.nip.io exposed via 0
--------------------------------------
Service Name: mysql-persistent
Type: mysql-persistent
Status: ProvisionedAndLinked
--------------------------------------
```

## Actual behavior
Does not honour manually created external route
```
- http://backend-node-example-app-myproject.192.168.64.3.nip.io exposed via 0
```

## Expected behavior
URLs details should be recognized as  ```- http://frontend-node-example-app-myproject.192.168.64.3.nip.io exposed via 8080```

**Comment by mohammedzee1000** [comment] 2019-02-04 11:44
@amitkrout are you still seeing this?

**Comment by amitkrout** [comment] 2019-02-04 11:54
@mohammedzee1000 No, please take it forward cc_ @geoand

**Comment by geoand** [comment] 2019-02-04 11:57
Well if the problem is gone, can we close this?

**Comment by mohammedzee1000** [comment] 2019-02-04 12:08
@geoand I would assume so, yes

**Closed** 2019-02-04 12:15 UTC
Labels: kind/bug, priority/Medium
