### ISSUE TITLE
java component does not work on pod restarts

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#927] opened 2018-11-05 16:12 UTC
[kind/bug]

## What versions of software are you using?

Version, latest from repository at time of writing.
```
$ odo version
odo v0.0.14 (da250f3)
```

## How did you run odo exactly?
```
$ odo project create roadshow
$ odo app create parksmap
$ oc adm policy add-role-to-user view -z default
$ git clone https://github.com/openshift-roadshow/parksmap-web
$ cd parksmap-web
$ odo create java web
$ odo push
$ odo url create --port 8080 --open
```

You should see now a map in the browser, which is the app.

Restart the pod. Scale it to 0 and scale it back to 1.

```
oc scale dc/web-parksmap --replicas=0
oc scale dc/web-parksmap --replicas=1
```

## Expected behavior

You should still see the map once the application restarts

## Actual behavior

The application is not available in the container. You need to push again. Also, all the .m2 cache is gone.

## Steps to reproduce the behavior

See above.

## Any logs, error output, etc?

When the pod has been restarted, you get this output, which is missing deployment.

```
+ set -eo pipefail
+ echo 'Setting up'
+ /var/lib/supervisord/bin/s2i-setup
Setting up
+ set -eo pipefail
+ mkdir -p /tmp/src
+ touch /tmp/src/.dummy
+ mkdir -p /opt/app-root/src
+ echo Running
+ /var/lib/supervisord/bin/run
Running
+ set -eo pipefail
+ '[' -f /opt/app-root/src/.s2i/bin/run ']'
+ '[' -f /usr/local/s2i/run ']'
+ exec /usr/local/s2i/run
Starting the Java application using /opt/run-java/run-java.sh ...
ERROR: Neither $JAVA_MAIN_CLASS nor $JAVA_APP_JAR is set and 0 JARs found in /deployments (1 expected)
exec java -javaagent:/opt/jolokia/jolokia.jar=config=/opt/jolokia/etc/jolokia.properties -Xms192m -Xmx768m -XX:+UseParallelOldGC -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:ParallelGCThreads=1 -Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -XX:CICompilerCount=2 -XX:+ExitOnOutOfMemoryError -cp . -jar
Error: -jar requires jar file specification
Usage: java [-options] class [args...]
           (to execute a class)
   or  java [-options] -jar jarfile [args...]
           (to execute a jar file)
where options include:
    -d32	  use a 32-bit data model if available
    -d64	  use a 64-bit data model if available
    -server	  to select the "server" VM
                  The default VM is server,
                  because you are running on a server-class machine.


    -cp <class search path of directories and zip/jar files>
    -classpath <class search path of directories and zip/jar files>
                  A : separated list of directories, JAR archives,
                  and ZIP archives to search for class files.
    -D<name>=<value>
                  set a system property
    -verbose:[class|gc|jni]
                  enable verbose output
    -version      print product version and exit
    -version:<value>
                  Warning: this feature is deprecated and will be removed
                  in a future release.
                  require the specified version to run
    -showversion  print product version and continue
    -jre-restrict-search | -no-jre-restrict-search
                  Warning: this feature is deprecated and will be removed
                  in a future release.
                  include/exclude user private JREs in the version search
    -? -help      print this help message
    -X            print help on non-standard options
    -ea[:<packagename>...|:<classname>]
    -enableassertions[:<packagename>...|:<classname>]
                  enable assertions with specified granularity
    -da[:<packagename>...|:<classname>]
    -disableassertions[:<packagename>...|:<classname>]
                  disable assertions with specified granularity
    -esa | -enablesystemassertions
                  enable system assertions
    -dsa | -disablesystemassertions
                  disable system assertions
    -agentlib:<libname>[=<options>]
                  load native agent library <libname>, e.g. -agentlib:hprof
                  see also, -agentlib:jdwp=help and -agentlib:hprof=help
    -agentpath:<pathname>[=<options>]
                  load native agent library by full pathname
    -javaagent:<jarpath>[=<options>]
                  load Java programming language agent, see java.lang.instrument
    -splash:<imagepath>
                  show splash screen with specified image
See http://www.oracle.com/technetwork/java/javase/documentation/index.html for more details.
time="2018-11-05T15:56:19Z" level=debug msg="wait program exit" program=run
time="2018-11-05T15:56:19Z" level=error msg="program stopped with error:exit status 1" program=run
time="2018-11-05T15:56:19Z" level=info msg="success to start program" program=run
```

## Do you have any idea what may have caused this?

The mount PV where the data is copied to preserve restarts is empty, hence the code/artifact that was pushed is not available.

## Do you have an idea how to solve the issue?

Properly place the persistent content in the image and re-configure the image to use the persistent location.

**Comment by kadel** [comment] 2018-11-08 12:38
closing this as a duplicate of #445

**Closed by kadel** 2018-11-08 12:38 UTC
Labels: kind/bug
