### ISSUE TITLE
Have ability to create environment variables through CLI

### ISSUE THREAD

**Issue by yohanswanepoel** [redhat-developer/odo#637] opened 2018-08-15 12:23 UTC
It would be useful to have an ability to define or set environment variables through the tooling. 

The 'link' option works for some but not all instances.

An example would be using environment variables to switch on/off capabilities in code or pointing at different versions of an API ect. I am sure there would be many more.

**Comment by mik-dass** [comment] 2018-08-15 14:29
There is a issue for this https://github.com/redhat-developer/odo/issues/501 and PR for the same https://github.com/redhat-developer/odo/pull/626

**Comment by mik-dass** [comment] 2018-09-10 10:01
Closing this as it's a duplicate of #501

**Closed by mik-dass** 2018-09-10 10:01 UTC
