### ISSUE TITLE
Bad character displayed when using odo on command-line on Windows 10

### ISSUE THREAD

**Issue by apupier** [redhat-developer/odo#1416] opened 2019-03-04 14:50 UTC
[kind/bug]

## What versions of software are you using?
- Operating System: Windows 10
- Output of `odo version`: odo v0.0.19 (61f278a1)

## How did you run odo exactly?

it was installed by VS Code OpenShift Connector.

## Actual behavior

strange characters are added

## Expected behavior

no strange character

## Any logs, error output, etc?

![image](https://user-images.githubusercontent.com/1105127/53740730-226b0900-3e95-11e9-9ce3-5eccd72bf04a.png)

same from command-line
![image](https://user-images.githubusercontent.com/1105127/53740743-28f98080-3e95-11e9-9e0d-8acf9db986c2.png)

I guess that it is because of color that are not supported

**Comment by kadel** [comment] 2019-03-05 11:22
this is duplicate of https://github.com/redhat-developer/odo/issues/1072

@apupier there is already a PR from  @cdrage that should fix this https://github.com/redhat-developer/odo/pull/1211

**Closed by kadel** 2019-03-05 11:22 UTC

**Comment by apupier** [comment] 2019-03-05 11:27
> this is duplicate of #1072

sorry, caught up not searching before if bug already exists (oops) :s

> @apupier there is already a PR from @cdrage that should fix this #1211

great, thanks!
