### ISSUE TITLE
odo push all the target directory content and not the binary file

### ISSUE THREAD

**Issue by cmoulliard** [redhat-developer/odo#950] opened 2018-11-08 09:32 UTC
## What versions of software are you using?

Operating System : macos

Output of `odo version` : odo v0.0.14 (618c6d3)

## How did you run odo exactly?

When we create a component to push a binary file using this command `odo create redhat-openjdk18-openshift:1.4 my-spring-boot --binary ./target/my-spring-boot-0.0.1-SNAPSHOT.jar` and next we do a `odo push`, then the content of the target directory is pushed

## Expected behavior

Only the binary file should be uploaded within the `/deployments` directory of the dev's pod and not all the files of the target directory

![screenshot 2018-11-08 10 29 56](https://user-images.githubusercontent.com/463790/48189877-7a5b8e00-e341-11e8-8319-73d56173fede.png)

![screenshot 2018-11-08 10 28 22](https://user-images.githubusercontent.com/463790/48189904-8a736d80-e341-11e8-9915-6f0665517aa2.png)

## Investigation

I suspect that the issue is coming from the fact that the tar file which is created and uploaded includes all the files of the directory `/opt/app-root/src` and not the binary file

![screenshot 2018-11-08 10 35 41](https://user-images.githubusercontent.com/463790/48190166-459c0680-e342-11e8-9df4-7a7f943ae27c.png)

**Comment by geoand** [comment] 2018-11-08 09:51
@cmoulliard I can confirm this issue exists even from the latest `master`. Although the behavior is not correct, it does not cause an problem. The Java s2i image is still perfectly capable of running the jar in the `/deployments` directory.
We should definitely look into fixing this based on your investigation, but I think we can live with it for the moment :)

**Comment by jorgemoralespou** [comment] 2018-11-08 11:43
@geond I disagree. We need to change this so that push only pushes the binary that is provided. It affects speed and can potentially affect behavior if there are multiple jar files in the target folder.

**Comment by geoand** [comment] 2018-11-08 11:54
@jorgemoralespou OK :)

**Comment by metacosm** [comment] 2018-11-08 15:12
@geoand pick it up, man! :)

**Comment by geoand** [comment] 2018-11-08 15:46
I am looking into this and although I have identified the problem I don't expect to have a fix anytime soon, basically because this is the first time that I am looking into go and kubernetes related IO code :)

**Comment by geoand** [comment] 2018-11-08 16:50
I created a [fix](https://github.com/redhat-developer/odo/pull/954) that I think works (tested it a few different scenarios and it works).
Please give it a try :)

**Comment by geoand** [comment] 2018-11-14 13:42
Fixed in: 7379c138

**Closed** 2018-11-14 13:42 UTC
Labels: kind/bug, priority/High, size/M, state/Ready
