### ISSUE TITLE
Component description has status/linkedServices filled with the same records

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/odo#5064] opened 2021-09-11 04:53 UTC
/kind bug

## What versions of software are you using?

**Operating System: Linux**

**Output of `odo version`: 2.2.3**

## How did you run odo exactly?

1. Created nodejs-ex component
2. Created postgrsql service
3. linked both 
4. pushed to cluster
5. Deleted from cluster
6. Repeated (4) and (5) 

## Actual behavior

Note status/linkedServices filled with duplicated objects.

```
{
  "kind": "List",
  "apiVersion": "odo.dev/v1alpha1",
  "metadata": {},
  "s2iComponents": [],
  "devfileComponents": [
    {
      "kind": "Component",
      "apiVersion": "odo.dev/v1alpha1",
      "metadata": {
        "name": "nodejs-ex",
        "namespace": "p1",
        "creationTimestamp": null
      },
      "spec": {
        "app": "app1",
        "type": "nodejs",
        "sourceType": "local",
        "url": [
          "http-3000"
        ],
        "env": [
          {
            "name": "PROJECTS_ROOT",
            "value": "/project"
          },
          {
            "name": "PROJECT_SOURCE",
            "value": "/project"
          },
          {
            "name": "DEBUG_PORT",
            "value": "5858"
          }
        ]
      },
      "status": {
        "state": "Pushed",
        "linkedServices": [
          {
            "ServiceName": "Database/database1",
            "SecretName": "nodejs-ex-database-database1-d1136801",
            "MountVolume": false,
            "MountPath": ""
          },
          {
            "ServiceName": "Database/database1",
            "SecretName": "nodejs-ex-database-database1-d1136801",
            "MountVolume": false,
            "MountPath": ""
          },
          {
            "ServiceName": "Database/database1",
            "SecretName": "nodejs-ex-database-database1-d1136801",
            "MountVolume": false,
            "MountPath": ""
          },
          {
            "ServiceName": "Database/database1",
            "SecretName": "nodejs-ex-database-database1-d1136801",
            "MountVolume": false,
            "MountPath": ""
          },
          {
            "ServiceName": "Database/database1",
            "SecretName": "nodejs-ex-database-database1-d1136801",
            "MountVolume": false,
            "MountPath": ""
          },
          {
            "ServiceName": "Database/database1",
            "SecretName": "nodejs-ex-database-database1-d1136801",
            "MountVolume": false,
            "MountPath": ""
          },
          {
            "ServiceName": "Database/database1",
            "SecretName": "nodejs-ex-database-database1-d1136801",
            "MountVolume": false,
            "MountPath": ""
          },
          {
            "ServiceName": "Database/database1",
            "SecretName": "nodejs-ex-database-database1-d1136801",
            "MountVolume": false,
            "MountPath": ""
          },
          {
            "ServiceName": "Database/database1",
            "SecretName": "nodejs-ex-database-database1-d1136801",
            "MountVolume": false,
            "MountPath": ""
          },
          {
            "ServiceName": "Database/database1",
            "SecretName": "nodejs-ex-database-database1-d1136801",
            "MountVolume": false,
            "MountPath": ""
          },
          {
            "ServiceName": "Database/database1",
            "SecretName": "nodejs-ex-database-database1-d1136801",
            "MountVolume": false,
            "MountPath": ""
          },
          {
            "ServiceName": "Database/database1",
            "SecretName": "nodejs-ex-database-database1-d1136801",
            "MountVolume": false,
            "MountPath": ""
          },
          {
            "ServiceName": "Database/database1",
            "SecretName": "nodejs-ex-database-database1-d1136801",
            "MountVolume": false,
            "MountPath": ""
          },
          {
            "ServiceName": "Database/database1",
            "SecretName": "nodejs-ex-database-database1-d1136801",
            "MountVolume": false,
            "MountPath": ""
          },
          {
            "ServiceName": "Database/database1",
            "SecretName": "nodejs-ex-database-database1-d1136801",
            "MountVolume": false,
            "MountPath": ""
          },
          {
            "ServiceName": "Database/database1",
            "SecretName": "nodejs-ex-database-database1-d1136801",
            "MountVolume": false,
            "MountPath": ""
          },
          {
            "ServiceName": "Database/database1",
            "SecretName": "nodejs-ex-database-database1-d1136801",
            "MountVolume": false,
            "MountPath": ""
          },
          {
            "ServiceName": "Database/database1",
            "SecretName": "nodejs-ex-database-database1-d1136801",
            "MountVolume": false,
            "MountPath": ""
          },
          {
            "ServiceName": "Database/database1",
            "SecretName": "nodejs-ex-database-database1-d1136801",
            "MountVolume": false,
            "MountPath": ""
          },
          {
            "ServiceName": "Database/database1",
            "SecretName": "nodejs-ex-database-database1-d1136801",
            "MountVolume": false,
            "MountPath": ""
          },
          {
            "ServiceName": "Database/database1",
            "SecretName": "nodejs-ex-database-database1-d1136801",
            "MountVolume": false,
            "MountPath": ""
          },
          {
            "ServiceName": "Database/database1",
            "SecretName": "nodejs-ex-database-database1-d1136801",
            "MountVolume": false,
            "MountPath": ""
          },
          {
            "ServiceName": "Database/database1",
            "SecretName": "nodejs-ex-database-database1-d1136801",
            "MountVolume": false,
            "MountPath": ""
          },
          {
            "ServiceName": "Database/database1",
            "SecretName": "nodejs-ex-database-database1-d1136801",
            "MountVolume": false,
            "MountPath": ""
          },
          {
            "ServiceName": "Database/database1",
            "SecretName": "nodejs-ex-database-database1-d1136801",
            "MountVolume": false,
            "MountPath": ""
          }
        ]
      }
    }
  ],
  "otherComponents": []
}

## Expected behavior

Should it be only one service in linkedServices instead?

## Any logs, error output, etc?

N/A

**Comment by valaparthvi** [comment] 2021-10-20 06:42
Were you able to reproduce this @dgolovin? And if yes, can you help me with this question:
>Delete what from the cluster, only the service, or the component, or both? Intuitively I went with deleting the service. I am not sure if this is operator specific, it should not be, but I will give it a shot with a Postgres operator. (https://github.com/openshift/odo/issues/5064#issuecomment-939950009)

I tried again, this time deleting the component itself from the cluster and pushing it, but, I was unable to reproduce it.

**Comment by valaparthvi** [comment] 2022-02-14 14:16
/close
Closing this in favor of v3 and the fact that it is not reproducible on v2 main.

Feel free to reopen if it's encountered again.

**Closed** 2022-02-14 14:16 UTC
Labels: kind/bug, priority/High, triage/needs-information
